import 'package:flutter_screenutil/flutter_screenutil.dart';

class AppCategories {
  static List<Map<String, dynamic>> lightingItemsData = [
    {
      "name": "panal",
      'first_name': 'Panel Type',
      'second_name': "panel watt",
      'thired_name': "panel Numbers",
      'forth_name': "panal Price",
      'icon': 'assets/images/categories_icons/sun_electric.png',
      'width': 130.w,
      'height': 92.28.h,
      'is_done': false,
    },
    {
      "name": "inverter",
      'first_name': 'Inverter Type',
      'second_name': "Inverter capacity",
      'thired_name': "Inverter Numbers",
      'forth_name': "Inverter price",
      'icon': 'assets/images/categories_icons/power_generator.png',
      'width': 96.w,
      'height': 112.h,
      'is_done': false,
    },
    {
      "name": "battery",
      'first_name': 'Chassis type',
      'second_name': "Type of chassis metal",
      'thired_name': "Chassis Numbers",
      'forth_name': "panal Price",
      'icon': 'assets/images/categories_icons/sun_battery.png',
      'width': 110.w,
      'height': 92.48.h,
      'is_done': false,
    },
    {
      "name": "chassis",
      'first_name': 'Panel Type',
      'second_name': "panel watt",
      'thired_name': "Number of panels",
      'forth_name': "panal Price",
      'icon': 'assets/images/categories_icons/stand_sun.png',
      'width': 130.w,
      'height': 106.41.h,
      'is_done': false,
    },
    {
      "name": "transportation",
      'first_name': 'Panel Type',
      'second_name': "panel watt",
      'thired_name': "Number of panels",
      'forth_name': "panal Price",
      'icon': 'assets/images/categories_icons/sun_system.png',
      'width': 120.w,
      'height': 115.12.h,
      'is_done': false,
    },
    {
      "name": "car_battrey",
      'first_name': 'Panel Type',
      'second_name': "panel watt",
      'thired_name': "Number of panels",
      'forth_name': "panal Price",
      'icon': 'assets/images/categories_icons/car_electric.png',
      'width': 144.22.w,
      'height': 140.22.h,
      'is_done': false,
    },
    // {
    //   'first_name': 'Panel Type',
    //   'second_name': "panel watt",
    //   'thired_name': "Number of panels",
    //   'forth_name': "panal Price",
    //   'icon': 'assets/images/categories_icons/settings.png',
    //   'width': 100.w,
    //   'height': 100.h,
    // },

    {
      "name": "persone",
      'first_name': 'Panel Type',
      'second_name': "panel watt",
      'thired_name': "Number of panels",
      'forth_name': "panal Price",
      'icon': 'assets/images/categories_icons/profile.png',
      'width': 95.22.w,
      'height': 100.h,
      'is_done': false,
    },
  ];
  static List<String> categoriesName = [
    "panal",
    "inverter",
    "battery",
    "chassis",
    "transportation",
    "car_battrey",
  ];
}
