# default_platform(:android)

# platform :android do
#   desc "Lane Android Firebase App Distribution"
#   lane :firebase_Distribution do
#     sh "flutter clean"
#     sh "flutter build apk --release --target lib/main.dart --no-tree-shake-icons"
#     firebase_app_distribution(
#     app: "1:322143888727:android:6d111c752f8f17671b8a12",
#     firebase_cli_token:"1//03nRWmz--Hes5CgYIARAAGAMSNwF-L9Ir-9GJ-Qr1OJCF_QSoTQwug7nnoR-2GEUtW0uyU4-Z-ygk3OqtwlI9uOdZO0JAFuz9oQ0"
#     # android_artifact_type:"APK",
#     android_artifact_path:"../build\app\outputs\flutter-apk\app-release.apk"
#     testers: "ibrahim13elgammal@gmail.com",
#     release_notes: "Lots of amazing new features to test out!"
#   )
#   end
# end

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase app Destribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
            app: "1:322143888727:android:6d111c752f8f17671b8a12",
            firebase_cli_token: "1//03nRWmz--Hes5CgYIARAAGAMSNwF-L9Ir-9GJ-Qr1OJCF_QSoTQwug7nnoR-2GEUtW0uyU4-Z-ygk3OqtwlI9uOdZO0JAFuz9oQ0",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
            testers: "ibrahim13elgammal@gmail.com, mohamedfawzi8898@gmail.com",
            release_notes: "- refactor some issus.
            - add customer screen form.
            - handle customer form screen data in cubit state management.
            - refactor add item code mecanism by added repo and database services class.
            - refactor error handler."
        )
  end
end